name: demo

on:
  workflow_dispatch:

jobs:
  login: 
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container registry
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: $GITHUB_USER
        password: $GITHUB_TOKEN
  
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pfichtner/freetz-toolchain-docker

    steps:
      - name: linux-release
        run: |
          cat /etc/*release

      - name: zstd
        run: |
          ldconfig -v 2>&1 | grep -B1 " libzstd.so\..*"

      - name: cpio
        run: |
          cpio --version

      - name: make
        run: |
          make --version

      - name: cmake
        run: |
          cmake --version

